- name: Install openssh-server
  apt:
    name: openssh-server
    state: present

- name: Create "ssh" group
  group:
    name: ssh
    state: present

- name: Configure sshd
  template:
    src: ssh_config.j2
    dest: /etc/ssh/sshd_config.d/override.conf
    owner: root
    group: root
    mode: "0644"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Restart sshd
